### ISSUE TITLE
`1人` is tokenized into single token while `6人` is not.

### ISSUE THREAD

**Issue by i10416** [WorksApplications/Sudachi#198]
`新任1人を含む6人の取締役の選任など3議案を原案通りに可決した` 

Could someone tell me why `1人` in the sentence above is tokenized into `1人` while `6人` is to `6` and `人`?

- Sudachi: 0.7.0
- sudachi-dictionary-20220729/system_core.dic

output
```
// surface: 新任, normalized: 新任, part of speach: 名詞,普通名詞,サ変可能,*,*,*, read: シンニン
// surface: 1人, normalized: 一人, part of speach: 名詞,普通名詞,副詞可能,*,*,*, read: ヒトリ
// surface: を, normalized: を, part of speach: 助詞,格助詞,*,*,*,*,  read: ヲ
// surface: 含む, normalized: 含む, part of speach: 動詞,一般,*,*,五段-マ行,連体形-一般,  read: フクム
// surface: 6, normalized: 6, part of speach: 名詞,数詞,*,*,*,*,  read: ロク
// surface: 人, normalized: 人, part of speach: 接尾辞,名詞的,一般,*,*,*, read: ニン
// ...
```

**Comment by kazuma-t** [comment]
This issue is a bit more complicated. 
The word 「1人」or 「一人」 is usually read as 「ヒトリ」, but this is an idiomatic reading, meaning that 「一」 and 「人」 cannot each have its own reading, and the whole 「一人」 is read as 「ヒトリ」.
On the other hand, 「6人」 can be divided into 「ロク」 and 「ニン」 respectively. Since it is not possible to register all numbers + 「人」 in the dictionary, all but 「一人」 and 「二人」 are divided into numbers and 「人」.

You may attach them together in post-processing.

**Comment by i10416** [comment]
Thanks！
