### ISSUE TITLE
Certain time-related words are pronounced incorrectly

### ISSUE THREAD

**Issue by version-mm** [WorksApplications/Sudachi#223]
二人は４時に出口の前で会います。  4時　should be よじ

二人は７月に出口の前で会います。　７月 should be　しちじ　

Not sure if it's a dictionary issue.
kuromoji does not have this problem

**Comment by azagniotov** [comment]
@version-mm , apologies for chiming in, where do you see that kuromoji does not have this problem? Solr or Elasticsearch?
e.g.: Solr field analysis UI? I am asking because Lucene Kuromoji tokenizer tokenizes `4時` as `4` and `時`, so is Sudachi tokenizer.

The Sudachi tokenizer does not expose `pronunciation` form, unlike Kuromoji.

**Comment by eiennohito** [comment]
@azagniotov pronunciation is available via filters however. The general design is to expose other fields via filters. The plugin implementation makes it so that several analysis chains stemming from the same tokenizer performs analysis of text only once.

**Comment by kazuma-t** [comment]
> $ echo 二人は４時に出口の前で会います。 | sudachipy -a
二人    名詞,普通名詞,副詞可能,*,*,*    二人    二人    フタリ  0       [13554]
は      助詞,係助詞,*,*,*,*     は      は      ハ      0       []
４      名詞,数詞,*,*,*,*       4       4       ヨン    0       [17063]
時      名詞,普通名詞,助数詞可能,*,*,*  時      時      ジ      0       []
に      助詞,格助詞,*,*,*,*     に      に      ニ      0       []
出口    名詞,普通名詞,一般,*,*,*        出口    出口    デグチ  0       []
の      助詞,格助詞,*,*,*,*     の      の      ノ      0       []
前      名詞,普通名詞,副詞可能,*,*,*    前      前      マエ    0       []
で      助詞,格助詞,*,*,*,*     で      で      デ      0       []
会い    動詞,一般,*,*,五段-ワア行,連用形-一般   会う    会う    アイ    0       []
ます    助動詞,*,*,*,助動詞-マス,終止形-一般    ます    ます    マス    0       []
。      補助記号,句点,*,*,*,*   。      。      。      0       []
EOS

> $ echo 二人は７月に出口の前で会います。 | sudachipy -a
二人    名詞,普通名詞,副詞可能,*,*,*    二人    二人    フタリ  0       [13554]
は      助詞,係助詞,*,*,*,*     は      は      ハ      0       []
７      名詞,数詞,*,*,*,*       7       7       ナナ    0       [16470]
月      名詞,普通名詞,助数詞可能,*,*,*  月      月      ガツ    0       []
に      助詞,格助詞,*,*,*,*     に      に      ニ      0       []
出口    名詞,普通名詞,一般,*,*,*        出口    出口    デグチ  0       []
の      助詞,格助詞,*,*,*,*     の      の      ノ      0       []
前      名詞,普通名詞,副詞可能,*,*,*    前      前      マエ    0       []
で      助詞,格助詞,*,*,*,*     で      で      デ      0       []
会い    動詞,一般,*,*,五段-ワア行,連用形-一般   会う    会う    アイ    0       []
ます    助動詞,*,*,*,助動詞-マス,終止形-一般    ます    ます    マス    0       []
。      補助記号,句点,*,*,*,*   。      。      。      0       []
EOS

The common reading for "4時" is "よじ" and "7月" is "しちがつ".

Sudachi gives the reading word by word, so it cannot output the correct reading of the numerals. To output the correct reading, you need to register "4時" or "7月" as a word.

Handling the reading of numerals in a unified manner, rather than word by word, requires a special mechanism, which Sudachi cannot immediately accommodate.

**Comment by kazuma-t** [comment]
Incidentally, it is not wrong to read "7月" as "なながつ".

**Comment by azagniotov** [comment]
> pronunciation



> @azagniotov pronunciation is available via filters however. The general design is to expose other fields via filters. The plugin implementation makes it so that several analysis chains stemming from the same tokenizer performs analysis of text only once.

Do you mean the `SudachiReadingFormFilter` which uses the `readingForm` of Morpheme? In Kuromoji Lucene they explicitly expose `getPronunciation` of the token, in addition to the `getReading`. Therefore, I said that Sudachi does not expose pronunciation 😅 Sorry for the misrepresentation

**Comment by version-mm** [comment]
> > $ echo 二人は４時に出口の前で会います。 | sudachipy -a
> > 二人    名詞,普通名詞,副詞可能,_,_,*    二人    二人    フタリ  0       [13554]
> > は      助詞,係助詞,_,_,_,_     は      は      ハ      0       []
> > ４      名詞,数詞,_,_,_,_       4       4       ヨン    0       [17063]
> > 時      名詞,普通名詞,助数詞可能,_,_,*  時      時      ジ      0       []
> > に      助詞,格助詞,_,_,_,_     に      に      ニ      0       []
> > 出口    名詞,普通名詞,一般,_,_,*        出口    出口    デグチ  0       []
> > の      助詞,格助詞,_,_,_,_     の      の      ノ      0       []
> > 前      名詞,普通名詞,副詞可能,_,_,*    前      前      マエ    0       []
> > で      助詞,格助詞,_,_,_,_     で      で      デ      0       []
> > 会い    動詞,一般,_,_,五段-ワア行,連用形-一般   会う    会う    アイ    0       []
> > ます    助動詞,_,_,_,助動詞-マス,終止形-一般    ます    ます    マス    0       []
> > 。      補助記号,句点,_,_,_,*   。      。      。      0       []
> > EOS
> 
> > $ echo 二人は７月に出口の前で会います。 | sudachipy -a
> > 二人    名詞,普通名詞,副詞可能,_,_,*    二人    二人    フタリ  0       [13554]
> > は      助詞,係助詞,_,_,_,_     は      は      ハ      0       []
> > ７      名詞,数詞,_,_,_,_       7       7       ナナ    0       [16470]
> > 月      名詞,普通名詞,助数詞可能,_,_,*  月      月      ガツ    0       []
> > に      助詞,格助詞,_,_,_,_     に      に      ニ      0       []
> > 出口    名詞,普通名詞,一般,_,_,*        出口    出口    デグチ  0       []
> > の      助詞,格助詞,_,_,_,_     の      の      ノ      0       []
> > 前      名詞,普通名詞,副詞可能,_,_,*    前      前      マエ    0       []
> > で      助詞,格助詞,_,_,_,_     で      で      デ      0       []
> > 会い    動詞,一般,_,_,五段-ワア行,連用形-一般   会う    会う    アイ    0       []
> > ます    助動詞,_,_,_,助動詞-マス,終止形-一般    ます    ます    マス    0       []
> > 。      補助記号,句点,_,_,_,*   。      。      。      0       []
> > EOS
> 
> The common reading for "4時" is "よじ" and "7月" is "しちがつ".
> 
> Sudachi gives the reading word by word, so it cannot output the correct reading of the numerals. To output the correct reading, you need to register "4時" or "7月" as a word.
> 
> Handling the reading of numerals in a unified manner, rather than word by word, requires a special mechanism, which Sudachi cannot immediately accommodate.
At this stage, can we handle these special readings by adding a user dictionary?

**Comment by version-mm** [comment]
> @version-mm , apologies for chiming in, where do you see that kuromoji does not have this problem? Solr or Elasticsearch? e.g.: Solr field analysis UI? I am asking because Lucene Kuromoji tokenizer tokenizes `4時` as `4` and `時`, so is Sudachi tokenizer.
> 
> The Sudachi tokenizer does not expose `pronunciation` form, unlike Kuromoji.
Directly through the following code
```java
import java.util.List;

import com.atilika.kuromoji.TokenizerBase.Mode;
import com.atilika.kuromoji.ipadic.Token;
import com.atilika.kuromoji.ipadic.Tokenizer;


public class JapaneseTextProcessor {
    public static void main(String[] args) {
        Tokenizer tokenizer = new Tokenizer.Builder()
        .mode(Mode.NORMAL)
        .build();
        List<Token> tokens = tokenizer.tokenize("二人は七月1日に出口の前で会います。");

        for (Token token : tokens) {
            System.out
                .println(token.getSurface() + "\t" + token.getReading() + "\t" + token.getPronunciation());
        }
    }

}
```
kuromoji has too many issues compared to Sudachi. For example, "1日" is not handled correctly by kuromoji
···csv 
七月  シチガツ    シチガツ 
1    *    *
 日   ニチ  ニチ 
 ···
, while Sudachi can correctly handle it as "ツイタチ".

**Comment by kazuma-t** [comment]
The reading of numerals is a difficult problem, and the reading may change depending on the context.

(I was told to finish the task by tomorrow.)
「1日では無理だ」(イチニチ)
(I was told to finish the task by July 1)
「1日では無理だ」(ツイタチ)

This is a problem that cannot be solved at the level of a tokenizer.

**Comment by azagniotov** [comment]
> > @version-mm , apologies for chiming in, where do you see that kuromoji does not have this problem? Solr or Elasticsearch? e.g.: Solr field analysis UI? I am asking because Lucene Kuromoji tokenizer tokenizes `4時` as `4` and `時`, so is Sudachi tokenizer.
> > The Sudachi tokenizer does not expose `pronunciation` form, unlike Kuromoji.
> > Directly through the following code
> 
> ```java
> import java.util.List;
> 
> import com.atilika.kuromoji.TokenizerBase.Mode;
> import com.atilika.kuromoji.ipadic.Token;
> import com.atilika.kuromoji.ipadic.Tokenizer;
> 
> 
> public class JapaneseTextProcessor {
>     public static void main(String[] args) {
>         Tokenizer tokenizer = new Tokenizer.Builder()
>         .mode(Mode.NORMAL)
>         .build();
>         List<Token> tokens = tokenizer.tokenize("二人は七月1日に出口の前で会います。");
> 
>         for (Token token : tokens) {
>             System.out
>                 .println(token.getSurface() + "\t" + token.getReading() + "\t" + token.getPronunciation());
>         }
>     }
> 
> }
> ```
> 
> kuromoji has too many issues compared to Sudachi. For example, "1日" is not handled correctly by kuromoji ···csv 七月 シチガツ シチガツ 1 * * 日 ニチ ニチ ··· , while Sudachi can correctly handle it as "ツイタチ".

Ah, thank you for clarification - you are using `Atilika`'s Kuromoji, not the Lucene's Kuromoji (i.e.: a Kuromoji tokenizer which is bundled together with the Lucene library. Originally Kuromoji was donated by Atilika to Apache Software Foundation, but by now Lucene's and Atilika Kuromoji codebases have diverged).
