### ISSUE TITLE
tokenizeSentences() consume huge memory for text is huge

### ISSUE THREAD

**Issue by kenmasumitsu** [WorksApplications/Sudachi#230]
With the changes in [Correctly split text into sentences #204](https://github.com/WorksApplications/Sudachi/pull/204), `JapaneseTokenizer.tokenizeSentences()` analyzed all characters.

Due to the changes, I see OpenSearch crashed with OOM.

In my investigation, 
`SentenceSplittingAnalysis.result` in `JapaneseTokenizer.tokenizeSentences()` becomes too large and consumes huge memories, when text is huge.
Could you change not to analyze all text in it?

**Comment by azagniotov** [comment]
@kazuma-t san, this is a big problem. Could you please take a look? @kenmasumitsu already implemented a fix in Sudachi Elasticsearch: https://github.com/WorksApplications/elasticsearch-sudachi/pull/132  Thank you! 🙏🏼

**Comment by kazuma-t** [comment]
We recognize the issue, but we cannot adopt the same solution as Es-sudachi. This approach may lead to incorrect sentence segmentation at buffer boundaries. In Es, adjusting the text length for input is not practical, so we reluctantly chose this method. However, Sudachi users can manually split their input at appropriate locations, rather than having the text split arbitrarily within Sudachi.

We plan to address this issue in a more suitable manner, but it will take some time.

**Comment by azagniotov** [comment]
@kazuma-t Understood. いつもありがとうございます。またよろしくお願いします。

**Comment by azagniotov** [comment]
Hello Team, @kazuma-t and @mh-northlander , I see a lot of good work in https://github.com/WorksApplications/Sudachi/pull/231, any updates when a new version of Sudachi will be released to Maven Central? 😃

**Comment by mh-northlander** [comment]
Close as #231 has released in v0.7.4.
